### PR TITLE
Request Audio With Desktop Share Only When The User Approves

### PR DESCRIPTION
**Pull request by chenqiang1986**
**Description**
We found that mediaDevices.getUserMedia does a strong check for the existence of requested track.
Namely, if we request an audio track, but Chromium cannot provide, getUserMedia will throw an exception rather than return a video-only stream. This behavior is aligned with the spec definition.

However, this brings some inconvenience in the desktop share with audio area, because on the media picker dialog, the end user could choose to uncheck the audio checkbox, and wish to get a video only stream. To resolve this dilemma, we change the Chromium a little bit to pass the information whether the user has checked or unchecked the audio to the callback function of chooseDesktopMedia, and then let following Javascript react correctly.

This change makes the mannual/peer2peer react correctly based on the newly added parameter.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Can you clarify something for me:
Currently only the Tab sharing option has an audio checkbox and it works fine while desktop and window screen share does not have the checkbox and requesting audio via GUM constraints for those fails.

Should the audio checkbox be present for all types of screen sharing?

**Comment by chenqiang1986** [comment]
That's limited by operating system api. 

1. We do not have api to capture audio stream for a single window for any platform.

2. The whole system audio loopback, we can only support for windows and chromeOS.

3. For tab, that's purely within chromium, and thus we can support for every platform.

**Comment by chenqiang1986** [comment]
The current issue is that if we cannot have audio stream (for whatever reason), and getUserMedia requests audio track, it will throw an exception.

So now we have to tell the Javascript whether one can or cannot request audio.

**Comment by KaptenJansson** [comment]
LGTM

**Comment by KaptenJansson** [comment]
Will fix the generic webdriver issue separately.

**Pull request merged**
