### PR TITLE
Polymer gum handler and dialog for testrtc

### PR DESCRIPTION
**Pull request by andresusanopinto**
For now added a 'closed' event so it can easily be wired up in current non-polymerized testrtc.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Something is preventing this from being rendered properly on Internet explorer (testing the gum not supported error). Last time one of the imports had a capital "i" which caused, cannot see anything that obvious now. IE is not presenting any useful info as usual.....

**Comment by KaptenJansson** [comment]
As we noted offline, all buttons became green in Safari, since we only want one button green it makes sense to remove paper-button in main.css and add color and background-color explicitly to "#start-button".

**Comment by andresusanopinto** [comment]
Fixed the CSS and the IE template if inside template ifs.

**Comment by andresusanopinto** [comment]
Fixed now with another change (threw out the old history).

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
